OutsourcerTracking/ViewComponents/AdminOperationListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace OutsourcerTracking.ViewComponents
{
    public class AdminOperationListViewComponent : ViewComponent
    {
        public ViewViewComponentResult Invoke()
        {
            return View();
        }
    }
}

OutsourcerTracking/ViewComponents/OutsourceListViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using OutsourcerTracking.Labels.Business.Abstract;
using OutsourcerTracking.Labels.DataAccess.Entities;
using OutsourcerTracking.Models.ViewComponentModels;
using System.Security.Claims;

namespace OutsourcerTracking.ViewComponents
{
    public class OutsourceListViewComponent : ViewComponent
    {
        private readonly UserManager<User> _userManager;
        private readonly IOutsourceService _outsourceService;
        public OutsourceListViewComponent(UserManager<User> userManager, IOutsourceService outsourceService)
        {
            _userManager = userManager;
            _outsourceService = outsourceService;
        }
        public ViewViewComponentResult Invoke()
        {
            var model = new OutsourceListViewComponentModel();
            if (HttpContext.User.IsInRole("Admin"))
            {
                model.Outsources = _outsourceService.GetAll();
            }
            else
            {
                User user = _userManager.GetUserAsync(HttpContext.User).Result;
                model.Outsources = _outsourceService.GetAllByOutsourceUserId(user.Id);
            }
            return View(model);
        }
    }
}

OutsourcerTracking/ViewComponents/WorkSituationListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using OutsourcerTracking.Labels.Business.Abstract;
using OutsourcerTracking.Models.ViewComponentModels;

namespace OutsourcerTracking.ViewComponents
{
    public class WorkSituationListViewComponent : ViewComponent
    {
        private readonly ISituationService _situationService;
        public WorkSituationListViewComponent(ISituationService situationService)
        {
            _situationService = situationService;
        }
        public ViewViewComponentResult Invoke()
        {
            var model = new WorkSituationListViewComponentModel
            {
                Situations = _situationService.GetAll()
            };
            return View(model);
        }
    }
}

OutsourcerTracking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OutsourcerTracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OutsourcerTracking.styles.css" asp-append-version="true" />
    
    <style>
        body{
            overflow-x: hidden;
        }
        .horizontal-padding-0 {
            padding-left: 0px;
            padding-right: 0px;
        }
        .horizontal-padding-1{
            padding-left: 0.5em;
            padding-right: 0.5em;
        }
        .horizontal-margin-1 {
            margin-left: 0.5em;
            margin-right: 0.5em;
        }
        .vertical-padding-1 {
            padding-bottom: 0.5em;
            padding-top: 0.5em;
        }
        .margin-1{
            margin: 0.5em 0.5em 0.5em 0.5em;
        }
        .padding-1{
            padding: 0.5em 0.5em 0.5em 0.5em;
        }
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OutsourcerTracking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a id="outsourceDropdownLink" href="#" class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Fasoncular</a>
                                <div class="dropdown-menu" aria-labelledby="outsourceDropdownLink">
                                    @await Component.InvokeAsync("OutsourceList")
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="workSituationDropdownLink" href="#" class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">İşler</a>
                                <div class="dropdown-menu" aria-labelledby="workSituationDropdownLink">
                                    @await Component.InvokeAsync("WorkSituationList")
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="adminOperationDropdownLink" href="#" class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin İşlemleri</a>
                                <div class="dropdown-menu" aria-labelledby="adminOperationDropdownLink">
                                    @await Component.InvokeAsync("AdminOperationList")
                                </div>
                            </li>
                        }
                        else if(User.IsInRole("Employee User"))
                        {
                            <li class="nav-item dropdown">
                                <a id="workSituationDropdownLink" href="#" class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">İşler</a>
                                <div class="dropdown-menu" aria-labelledby="workSituationDropdownLink">
                                    @await Component.InvokeAsync("WorkSituationList")
                                </div>
                            </li>
                        }
                        else if (User.IsInRole("Outsource User"))
                        {
                            <li class="nav-item dropdown">
                                <a id="outsourceDropdownLink" href="#" class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Fasoncular</a>
                                <div class="dropdown-menu" aria-labelledby="outsourceDropdownLink">
                                    @await Component.InvokeAsync("OutsourceList")
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav"> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/UserAuthentication/Logout">Çıkış</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div class="col-lg-2 horizontal-padding-0 d-none d-sm-none d-md-none d-lg-block">
            @if (User.IsInRole("Admin"))
            {
                <div class="accordion" id="accordionExample">
                    <div class="nav-item border">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                Fasoncular
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body horizontal-padding-0">
                                @await Component.InvokeAsync("OutsourceList")
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                İşler
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                            <div class="accordion-body horizontal-padding-0">
                                @await Component.InvokeAsync("WorkSituationList")
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Admin İşlemleri
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                            <div class="accordion-body horizontal-padding-0">
                                @await Component.InvokeAsync("AdminOperationList")
                            </div>
                        </div>
                    </div>
                </div>
            }
            else if (User.IsInRole("Employee User"))
            {
                <div class="nav-item border">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            İşler
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body horizontal-padding-0">
                            @await Component.InvokeAsync("WorkSituationList")
                        </div>
                    </div>
                </div>
            }
            else if (User.IsInRole("Outsource User"))
            {
                <div class="nav-item border">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            Fasoncular
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body horizontal-padding-0">
                            @await Component.InvokeAsync("OutsourceList")
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-lg-10 horizontal-padding-0">
            @RenderBody()
        </div>
    </div>
    
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OutsourcerTracking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js" integrity="sha512-FHZVRMUW9FsXobt+ONiix6Z0tIkxvQfxtCSirkKc5Sb4TKHmqq1dZa8DphF0XqKb3ldLu/wgMa8mT6uXiLlRlw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OutsourcerTracking/Views/Shared/_LayoutAddEdit.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OutsourcerTracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OutsourcerTracking.styles.css" asp-append-version="true" />

    <style>
        body {
            overflow-x: hidden;
        }

        .horizontal-padding-0 {
            padding-left: 0px;
            padding-right: 0px;
        }

        .horizontal-padding-1 {
            padding-left: 0.5em;
            padding-right: 0.5em;
        }

        .horizontal-margin-1 {
            margin-left: 0.5em;
            margin-right: 0.5em;
        }

        .vertical-padding-1 {
            padding-bottom: 0.5em;
            padding-top: 0.5em;
        }

        .margin-1 {
            margin: 0.5em 0.5em 0.5em 0.5em;
        }

        .padding-1 {
            padding: 0.5em 0.5em 0.5em 0.5em;
        }

        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OutsourcerTracking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js" integrity="sha512-FHZVRMUW9FsXobt+ONiix6Z0tIkxvQfxtCSirkKc5Sb4TKHmqq1dZa8DphF0XqKb3ldLu/wgMa8mT6uXiLlRlw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OutsourcerTracking/Views/Shared/_LayoutUserAuthentication.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OutsourcerTracking.styles.css" asp-append-version="true" />
    <style>
        .horizontal-padding-0 {
            padding-left: 0px;
            padding-right: 0px;
        }
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center mt-5">
        <div class="card shadow-sm p-3 mb-5 bg-white rounded" style="width: 30rem;">
            <div class="card-header">
                <h4>@ViewBag.Title</h4>
            </div>
            <div class="card-body">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>