OutsourcerTracking/Models/EmployeeUserModels/EmployeeUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OutsourcerTracking.Models.EmployeeUserModels
{
    public class EmployeeUserViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string RoleName { get; set; }
        public string DepartmentName { get; set; }
        public string TitleName { get; set; }
    }
}

OutsourcerTracking/Controllers/EmployeeUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OutsourcerTracking.Labels.Business.Abstract;
using OutsourcerTracking.Models.EmployeeUserModels;
using System.Data;

namespace OutsourcerTracking.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeeUserController : Controller
    {
        private readonly IEmployeeUserService _employeeUserService;
        private readonly IRoleService _roleService;
        private readonly IDepartmentService _departmentService;
        private readonly ITitleService _titleService;
        public EmployeeUserController(IEmployeeUserService employeeUserService, IRoleService roleService, IDepartmentService departmentService, ITitleService titleService)
        {
            _employeeUserService = employeeUserService;
            _roleService = roleService;
            _departmentService = departmentService;
            _titleService = titleService;
        }
        public IActionResult Index()
        {
            var model = new EmployeeUserListViewModel
            {
                EmployeeUsers = _employeeUserService.GetAllFullRelation()
            };
            return View(model);
        }
        public IActionResult Create()
        {
            List<SelectListItem> roleList = _roleService.GetAllEmployeeRoles().ToList().Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList();
            ViewBag.roles = roleList;
            List<SelectListItem> departmanList = _departmentService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
            ViewBag.departments = departmanList;
            List<SelectListItem> titleList = _titleService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
            ViewBag.titles = titleList;
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeUserCreateViewModel createVM)
        {
            if (!ModelState.IsValid)
            {
                List<SelectListItem> roleList = _roleService.GetAllEmployeeRoles().ToList().Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList();
                ViewBag.roles = roleList;
                List<SelectListItem> departmanList = _departmentService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
                ViewBag.departments = departmanList;
                List<SelectListItem> titleList = _titleService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
                ViewBag.titles = titleList;
                return View(createVM);
            }
            _employeeUserService.AddRelational(createVM, HttpContext.User.Identity.Name);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int Id)
        {
            List<SelectListItem> roleList = _roleService.GetAllEmployeeRoles().ToList().Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList();
            ViewBag.roles = roleList;
            List<SelectListItem> departmanList = _departmentService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
            ViewBag.departments = departmanList;
            List<SelectListItem> titleList = _titleService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
            ViewBag.titles = titleList;
            var updateEmployeeUser = _employeeUserService.GetRealtionalById(Id);
            return View(updateEmployeeUser);
        }
        [HttpPost]
        public IActionResult Edit(EmployeeUserEditViewModel editVM)
        {
            if(!ModelState.IsValid)
            {
                List<SelectListItem> roleList = _roleService.GetAllEmployeeRoles().ToList().Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList();
                ViewBag.roles = roleList;
                List<SelectListItem> departmanList = _departmentService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
                ViewBag.departments = departmanList;
                List<SelectListItem> titleList = _titleService.GetAll().Select(d => new SelectListItem { Value = d.Id.ToString(), Text = d.Name }).ToList();
                ViewBag.titles = titleList;
                return View(editVM);
            }
            _employeeUserService.EditRelational(editVM, HttpContext.User.Identity.Name);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            _employeeUserService.Delete(id, HttpContext.User.Identity.Name);
            return RedirectToAction(nameof(Index));
        }
    }
}

OutsourcerTracking/Views/EmployeeUser/Create.cshtml
@model OutsourcerTracking.Models.EmployeeUserModels.EmployeeUserCreateViewModel
@{
    ViewData["Title"] = "Yeni Çalışan Kullancı Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="horizontal-margin-1">
    <h1 class="text-center">@ViewData["Title"]</h1>

    @using (Html.BeginForm("Create", "EmployeeUser", FormMethod.Post))
    {
        <div class="form-group horizontal-margin-1">
            <div class="row">
                <div class="col-md-6">
                    @Html.TextBoxFor(m => m.FirstName,  new {@class = "form-control", placeholder="Ad"})
                    @Html.ValidationMessageFor(m => m.FirstName, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.LastName,  new {@class = "form-control", placeholder="Soyad"})
                    @Html.ValidationMessageFor(m => m.LastName, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.Email,  new {@class = "form-control", placeholder="Eposta"})
                    @Html.ValidationMessageFor(m => m.Email, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.Phone,  new {@class = "form-control", placeholder="Telefon"})
                    @Html.ValidationMessageFor(m => m.Phone, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.Password,  new {@class = "form-control", placeholder="Şifre", type="password"})
                    @Html.ValidationMessageFor(m => m.Password, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.PasswordConfirm, new {@class = "form-control", placeholder="Şifre Tekrar", type="password"})
                    @Html.ValidationMessageFor(m => m.PasswordConfirm, null, new {@class="text-danger"})
                    <br />
                </div>
                <div class="col-md-6">
                    @Html.Label("Rol")
                    @Html.DropDownListFor(m => m.RoleId, (List<SelectListItem>)ViewBag.roles, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.RoleId, null, new {@class="text-danger"})
                    <br />
                    @Html.Label("Bölüm")
                    @Html.DropDownListFor(m => m.DeparmentId, (List<SelectListItem>)ViewBag.departments, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.DeparmentId, null, new {@class="text-danger"})
                    <br />
                    @Html.Label("Ünvan")
                    @Html.DropDownListFor(m => m.TitleId, (List<SelectListItem>)ViewBag.titles, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.TitleId, null, new {@class="text-danger"})
                    <br />
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Ekle</button>
        </div>
    }
</div>

<script type="text/javascript">
    $(function () {
        $('.listbox').multiselect({
            includeSelectAllOption: true
        });
    });
</script>

OutsourcerTracking/Views/EmployeeUser/Edit.cshtml
@model OutsourcerTracking.Models.EmployeeUserModels.EmployeeUserEditViewModel
@{
    ViewData["Title"] = "Çalışan Kullanıcı Düzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="horizontal-margin-1">
    <h1 class="text-center">@ViewData["Title"]</h1>
    @using (Html.BeginForm("Edit", "EmployeeUser", FormMethod.Post))
    {
        <div class="form-group vertical-padding-1 horizontal-margin-1">
            <div class="row">
                <div class="col-md-6">
                    @Html.TextBoxFor(m => m.FirstName,  new {@class = "form-control", placeholder="Ad"})
                    @Html.ValidationMessageFor(m => m.FirstName, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.LastName,  new {@class = "form-control", placeholder="Soyad"})
                    @Html.ValidationMessageFor(m => m.LastName, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.Email,  new {@class = "form-control", placeholder="Eposta"})
                    @Html.ValidationMessageFor(m => m.Email, null, new {@class="text-danger"})
                    <br />
                    @Html.TextBoxFor(m => m.Phone,  new {@class = "form-control", placeholder="Telefon"})
                    @Html.ValidationMessageFor(m => m.Phone, null, new {@class="text-danger"})
                    <br />
                </div>
                <div class="col-md-6">
                    @Html.Label("Rol")
                    @Html.DropDownListFor(m => m.RoleId, (List<SelectListItem>)ViewBag.roles, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.RoleId, null, new {@class="text-danger"})
                    <br />
                    @Html.Label("Bölüm")
                    @Html.DropDownListFor(m => m.DeparmentId, (List<SelectListItem>)ViewBag.departments, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.DeparmentId, null, new {@class="text-danger"})
                    <br />
                    @Html.Label("Ünvan")
                    @Html.DropDownListFor(m => m.TitleId, (List<SelectListItem>)ViewBag.titles, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.TitleId, null, new {@class="text-danger"})
                    <br />
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Düzenle</button>
        </div>
    }
</div>

OutsourcerTracking/Views/EmployeeUser/Index.cshtml
@model OutsourcerTracking.Models.EmployeeUserModels.EmployeeUserListViewModel;

@{
    ViewData["Title"] = "Çalışan Kullanıcıları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="horizontal-margin-1">
    <h1 class="text-center">@ViewData["Title"]</h1>
    <div class="margin-1"><a href="/employeeuser/create"><button type="button" class="btn btn-success">Yeni</button></a></div>
    <hr />
    <div class="horizontal-margin-1">
        <table id="myTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Ad</th>
                    <th>Soyad</th>
                    <th>Eposta</th>
                    <th>Telefon</th>
                    <th>Bölüm</th>
                    <th>Ünvan</th>
                    <th>Rol</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var employeeUserVM in Model.EmployeeUsers)
                {
                    <tr>
                        <td>@employeeUserVM.FirstName</td>
                        <td>@employeeUserVM.LastName</td>
                        <td>@employeeUserVM.Email</td>
                        <td>@employeeUserVM.Phone</td>
                        <td>@employeeUserVM.DepartmentName</td>
                        <td>@employeeUserVM.TitleName</td>
                        <td>@employeeUserVM.RoleName</td>
                        <td>
                            <a href="/employeeuser/edit/@employeeUserVM.Id">
                                <button type="button" class="btn btn-primary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                                    </svg>
                                </button>
                            </a>
                            <a href="#">
                                <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-archive" viewBox="0 0 16 16">
                                        <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"></path>
                                    </svg>
                                </button>
                            </a>
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Kullanıcıyı Sil</h5>
                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            "@employeeUserVM.FirstName @employeeUserVM.LastName" adlı kullanıcıyı silmek istediğinizden emin misiniz?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">İptal</button>
                                            <a href="/employeeuser/delete/@employeeUserVM.Id"><button type="button" class="btn btn-danger">Sil</button></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.css" />
<script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.js"></script>
<script>
    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        js('#myTable').DataTable({
            scrollX: true,
            language: {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
            }
        });
    });
</script>