OutsourcerTracking/Controllers/UserAuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis;
using OutsourcerTracking.Controllers.Homes;
using OutsourcerTracking.Labels.Business.Abstract;
using OutsourcerTracking.Labels.Business.Concrete;
using OutsourcerTracking.Labels.DataAccess.Entities;
using OutsourcerTracking.Models.UserAuthenticationModels;

namespace OutsourcerTracking.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private readonly IUserAuthenticationService _userAuthenticationService;
        public UserAuthenticationController(IUserAuthenticationService userAuthenticationService)
        {
            _userAuthenticationService = userAuthenticationService;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserAuthenticationLoginViewModel loginVM) 
        {
            if (!ModelState.IsValid)
            {
                return View(loginVM);
            }
            var result = await _userAuthenticationService.LoginAsync(loginVM);
            if(result.Success)
            {
                if (result.Object.IsFirst)
                    return RedirectToAction(nameof(UserAuthenticationController.ChangePassword), nameof(UserAuthenticationController).Replace("Controller", ""));
                else
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }
        }
        public async Task<IActionResult> LogoutAsync()
        {
            await _userAuthenticationService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }
        public async Task<IActionResult> ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel changePasswordModel)
        {
            if (!ModelState.IsValid)
            {
                return View(changePasswordModel);
            }
            _userAuthenticationService.ChangePassword(HttpContext.User.Identity.Name, changePasswordModel.NewPassword);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
        }
        public async Task<IActionResult> ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgetPassword(ForgetPasswordModel forgetPasswordModel)
        {
            if(!ModelState.IsValid)
            {
                return View(forgetPasswordModel);
            }
            var result = await _userAuthenticationService.CheckEmail(forgetPasswordModel.Email);
            if (result.Success)
            {
                _userAuthenticationService.RecordKeyCode(forgetPasswordModel.Email);
                return RedirectToAction(nameof(NewPassword));

            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(ForgetPassword));
            }
    
        }
        public async Task<IActionResult> NewPassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NewPassword(NewPasswordModel newPasswordModel)
        {
            if (!ModelState.IsValid)
            {
                return View(newPasswordModel);
            }
            else
            {
                var result= _userAuthenticationService.ChangePasswordWithKeyCode(newPasswordModel.key, newPasswordModel.newpassword);
                if (result.Success)
                {
                    return RedirectToAction(nameof(Login));
                }
                else
                {
                    TempData["msg"] = result.Message;
                    return RedirectToAction(nameof(NewPassword));
                }
               
            }
        }
    }
}

OutsourcerTracking/Views/UserAuthentication/ChangePassword.cshtml
@model OutsourcerTracking.Models.UserAuthenticationModels.ChangePasswordModel;
@{
    ViewBag.Title = "Şifre Değiştir";
    Layout = "~/Views/Shared/_LayoutUserAuthentication.cshtml";
}
<div>
    @if (TempData["msg"] != null)
    {
        <div class="alert alert-danger" role="alert">@TempData["msg"]</div>
    }
    @using (Html.BeginForm("ChangePassword", "UserAuthentication", FormMethod.Post))
    {
        <div class="form-group vertical-padding-1">
            @Html.TextBoxFor(m => m.oldPassword,  new {@class = "form-control", placeholder="Eski Şifre", type="password"})
            @Html.ValidationMessageFor(m => m.oldPassword, null, new {@class="text-danger"})
            <br />
            @Html.TextBoxFor(m => m.NewPassword,  new {@class = "form-control", placeholder="Şifre", type="password"})
            @Html.ValidationMessageFor(m => m.NewPassword, null, new {@class="text-danger"})
            <br />
            @Html.TextBoxFor(m => m.NewPasswordAgain,  new {@class = "form-control", placeholder="Şifre", type="password"})
            @Html.ValidationMessageFor(m => m.NewPasswordAgain, null, new {@class="text-danger"})
            <br />
            <button type="submit" class="btn btn-primary">Değiştir</button>
        </div>
    }
</div>

OutsourcerTracking/Views/UserAuthentication/ForgetPassword.cshtml
@model OutsourcerTracking.Models.UserAuthenticationModels.ForgetPasswordModel;
@{
    ViewBag.Title = "Şifremi Unuttum";
    Layout = "~/Views/Shared/_LayoutUserAuthentication.cshtml";
}
<div>
    @if (TempData["msg"] != null)
    {
        <div class="alert alert-danger" role="alert">@TempData["msg"]</div>
    }
    @using (Html.BeginForm("ForgetPassword", "UserAuthentication", FormMethod.Post))
    {
        <div class="form-group vertical-padding-1">
            @Html.TextBoxFor(m => m.Email,  new {@class = "form-control", placeholder="E-Posta"})
            @Html.ValidationMessageFor(m => m.Email, null, new {@class="text-danger"})
            <br />
            <button type="submit" class="btn btn-primary">Gönder</button>
        </div>
    }
</div>

OutsourcerTracking/Views/UserAuthentication/Login.cshtml
@model OutsourcerTracking.Models.UserAuthenticationModels.UserAuthenticationLoginViewModel;
@{
    ViewBag.Title = "Giriş Yap";
    Layout = "~/Views/Shared/_LayoutUserAuthentication.cshtml";
}
<div>
    @if (TempData["msg"] != null)
    {
        <div class="alert alert-danger" role="alert">@TempData["msg"]</div>
    }
    @using (Html.BeginForm("Login", "UserAuthentication", FormMethod.Post))
    {
        <div class="form-group vertical-padding-1">
            @Html.TextBoxFor(m => m.Email,  new {@class = "form-control", placeholder="Email"})
            @Html.ValidationMessageFor(m => m.Email, null, new {@class="text-danger"})
            <br />
            @Html.TextBoxFor(m => m.Password,  new {@class = "form-control", placeholder="Şifre", type="password"})
            @Html.ValidationMessageFor(m => m.Password, null, new {@class="text-danger"})
            <br />
            @Html.ActionLink("Şifremi Unuttum", "ForgetPassword","UserAuthentication")

            <br>
            <button type="submit" class="btn btn-primary">Giriş</button>
        </div>
    }
</div>

OutsourcerTracking/Views/UserAuthentication/NewPassword.cshtml
@model OutsourcerTracking.Models.UserAuthenticationModels.NewPasswordModel;
@{
    ViewBag.Title = "Yeni Şifre";
    Layout = "~/Views/Shared/_LayoutUserAuthentication.cshtml";
}
<div>
    @if (TempData["msg"] != null)
    {
        <div class="alert alert-danger" role="alert">@TempData["msg"]</div>
    }
    @using (Html.BeginForm("NewPassword", "UserAuthentication", FormMethod.Post))
    {
        <div class="form-group vertical-padding-1">
            @Html.TextBoxFor(m => m.key,  new {@class = "form-control",placeholder="Güvenlik Kodu",type="text"} )
            @Html.ValidationMessageFor(m => m.key, null, new {@class="text-danger"})
            <br />
            @Html.TextBoxFor(m => m.newpassword,  new {@class = "form-control",placeholder="Şifre", type="password"} )
            @Html.ValidationMessageFor(m => m.newpassword, null, new {@class="text-danger"})
            <br />
            @Html.TextBoxFor(m => m.newpassword2,  new {@class = "form-control",placeholder="Şifre Tekrar", type="password"})
            @Html.ValidationMessageFor(m => m.newpassword2, null, new {@class="text-danger"})
            <br>
            <button type="submit" class="btn btn-primary">Gönder</button>
        </div>
    }
</div>